# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'win.ui'
##
## Created by: Qt User Interface Compiler version 6.3.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QLabel, QMainWindow,
    QMenuBar, QPushButton, QSizePolicy, QStatusBar,
    QTextBrowser, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1260, 810)
        MainWindow.setMinimumSize(QSize(1260, 590))
        MainWindow.setMaximumSize(QSize(1260, 810))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.comboBox = QComboBox(self.centralwidget)
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(970, 5, 231, 32))
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(1210, 5, 41, 32))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(0, 0, 960, 540))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(680, 580, 280, 158))
        self.label_w = QLabel(self.centralwidget)
        self.label_w.setObjectName(u"label_w")
        self.label_w.setGeometry(QRect(180, 600, 30, 30))
        self.label_w.setAutoFillBackground(False)
        self.label_w.setStyleSheet(u"background-color:rgb(209, 209, 209)")
        self.label_w.setAlignment(Qt.AlignCenter)
        self.label_s = QLabel(self.centralwidget)
        self.label_s.setObjectName(u"label_s")
        self.label_s.setGeometry(QRect(180, 660, 30, 30))
        self.label_s.setAutoFillBackground(False)
        self.label_s.setStyleSheet(u"background-color:rgb(209, 209, 209)")
        self.label_s.setAlignment(Qt.AlignCenter)
        self.label_a = QLabel(self.centralwidget)
        self.label_a.setObjectName(u"label_a")
        self.label_a.setGeometry(QRect(150, 630, 30, 30))
        self.label_a.setAutoFillBackground(False)
        self.label_a.setStyleSheet(u"background-color:rgb(209, 209, 209)")
        self.label_a.setAlignment(Qt.AlignCenter)
        self.label_d = QLabel(self.centralwidget)
        self.label_d.setObjectName(u"label_d")
        self.label_d.setGeometry(QRect(210, 630, 30, 30))
        self.label_d.setAutoFillBackground(False)
        self.label_d.setStyleSheet(u"background-color:rgb(209, 209, 209)")
        self.label_d.setAlignment(Qt.AlignCenter)
        self.label_f = QLabel(self.centralwidget)
        self.label_f.setObjectName(u"label_f")
        self.label_f.setGeometry(QRect(250, 650, 30, 30))
        self.label_f.setAutoFillBackground(False)
        self.label_f.setStyleSheet(u"background-color:rgb(209, 209, 209)")
        self.label_f.setAlignment(Qt.AlignCenter)
        self.label_c = QLabel(self.centralwidget)
        self.label_c.setObjectName(u"label_c")
        self.label_c.setGeometry(QRect(220, 680, 30, 30))
        self.label_c.setAutoFillBackground(False)
        self.label_c.setStyleSheet(u"background-color:rgb(209, 209, 209)")
        self.label_c.setAlignment(Qt.AlignCenter)
        self.label_b = QLabel(self.centralwidget)
        self.label_b.setObjectName(u"label_b")
        self.label_b.setGeometry(QRect(280, 680, 30, 30))
        self.label_b.setAutoFillBackground(False)
        self.label_b.setStyleSheet(u"background-color:rgb(209, 209, 209)")
        self.label_b.setAlignment(Qt.AlignCenter)
        self.label_v = QLabel(self.centralwidget)
        self.label_v.setObjectName(u"label_v")
        self.label_v.setGeometry(QRect(250, 710, 30, 30))
        self.label_v.setAutoFillBackground(False)
        self.label_v.setStyleSheet(u"background-color:rgb(209, 209, 209)")
        self.label_v.setAlignment(Qt.AlignCenter)
        self.label_rl = QLabel(self.centralwidget)
        self.label_rl.setObjectName(u"label_rl")
        self.label_rl.setGeometry(QRect(360, 680, 30, 30))
        self.label_rl.setAutoFillBackground(False)
        self.label_rl.setStyleSheet(u"background-color:rgb(209, 209, 209)")
        self.label_rl.setAlignment(Qt.AlignCenter)
        self.label_rr = QLabel(self.centralwidget)
        self.label_rr.setObjectName(u"label_rr")
        self.label_rr.setGeometry(QRect(420, 680, 30, 30))
        self.label_rr.setAutoFillBackground(False)
        self.label_rr.setStyleSheet(u"background-color:rgb(209, 209, 209)")
        self.label_rr.setAlignment(Qt.AlignCenter)
        self.label_rt = QLabel(self.centralwidget)
        self.label_rt.setObjectName(u"label_rt")
        self.label_rt.setGeometry(QRect(390, 650, 30, 30))
        self.label_rt.setAutoFillBackground(False)
        self.label_rt.setStyleSheet(u"background-color:rgb(209, 209, 209)")
        self.label_rt.setAlignment(Qt.AlignCenter)
        self.label_rb = QLabel(self.centralwidget)
        self.label_rb.setObjectName(u"label_rb")
        self.label_rb.setGeometry(QRect(390, 710, 30, 30))
        self.label_rb.setAutoFillBackground(False)
        self.label_rb.setStyleSheet(u"background-color:rgb(209, 209, 209)")
        self.label_rb.setAlignment(Qt.AlignCenter)
        self.label_j = QLabel(self.centralwidget)
        self.label_j.setObjectName(u"label_j")
        self.label_j.setGeometry(QRect(430, 630, 30, 30))
        self.label_j.setAutoFillBackground(False)
        self.label_j.setStyleSheet(u"background-color:rgb(209, 209, 209)")
        self.label_j.setAlignment(Qt.AlignCenter)
        self.label_i = QLabel(self.centralwidget)
        self.label_i.setObjectName(u"label_i")
        self.label_i.setGeometry(QRect(460, 600, 30, 30))
        self.label_i.setAutoFillBackground(False)
        self.label_i.setStyleSheet(u"background-color:rgb(209, 209, 209)")
        self.label_i.setAlignment(Qt.AlignCenter)
        self.label_l = QLabel(self.centralwidget)
        self.label_l.setObjectName(u"label_l")
        self.label_l.setGeometry(QRect(490, 630, 30, 30))
        self.label_l.setAutoFillBackground(False)
        self.label_l.setStyleSheet(u"background-color:rgb(209, 209, 209)")
        self.label_l.setAlignment(Qt.AlignCenter)
        self.label_k = QLabel(self.centralwidget)
        self.label_k.setObjectName(u"label_k")
        self.label_k.setGeometry(QRect(460, 660, 30, 30))
        self.label_k.setAutoFillBackground(False)
        self.label_k.setStyleSheet(u"background-color:rgb(209, 209, 209)")
        self.label_k.setAlignment(Qt.AlignCenter)
        self.label_y = QLabel(self.centralwidget)
        self.label_y.setObjectName(u"label_y")
        self.label_y.setGeometry(QRect(380, 590, 30, 30))
        self.label_y.setAutoFillBackground(False)
        self.label_y.setStyleSheet(u"background-color:rgb(209, 209, 209)")
        self.label_y.setAlignment(Qt.AlignCenter)
        self.label_r = QLabel(self.centralwidget)
        self.label_r.setObjectName(u"label_r")
        self.label_r.setGeometry(QRect(260, 590, 30, 30))
        self.label_r.setAutoFillBackground(False)
        self.label_r.setStyleSheet(u"background-color:rgb(209, 209, 209)")
        self.label_r.setAlignment(Qt.AlignCenter)
        self.label_h = QLabel(self.centralwidget)
        self.label_h.setObjectName(u"label_h")
        self.label_h.setGeometry(QRect(350, 620, 30, 30))
        self.label_h.setAutoFillBackground(False)
        self.label_h.setStyleSheet(u"background-color:rgb(209, 209, 209)")
        self.label_h.setAlignment(Qt.AlignCenter)
        self.label_g = QLabel(self.centralwidget)
        self.label_g.setObjectName(u"label_g")
        self.label_g.setGeometry(QRect(290, 620, 30, 30))
        self.label_g.setAutoFillBackground(False)
        self.label_g.setStyleSheet(u"background-color:rgb(209, 209, 209)")
        self.label_g.setAlignment(Qt.AlignCenter)
        self.label_x = QLabel(self.centralwidget)
        self.label_x.setObjectName(u"label_x")
        self.label_x.setGeometry(QRect(185, 635, 20, 20))
        self.label_x.setAutoFillBackground(False)
        self.label_x.setStyleSheet(u"background-color:rgb(209, 209, 209)")
        self.label_x.setAlignment(Qt.AlignCenter)
        self.label_rc = QLabel(self.centralwidget)
        self.label_rc.setObjectName(u"label_rc")
        self.label_rc.setGeometry(QRect(395, 685, 20, 20))
        self.label_rc.setAutoFillBackground(False)
        self.label_rc.setStyleSheet(u"background-color:rgb(209, 209, 209)")
        self.label_rc.setAlignment(Qt.AlignCenter)
        self.label_e = QLabel(self.centralwidget)
        self.label_e.setObjectName(u"label_e")
        self.label_e.setGeometry(QRect(80, 600, 60, 25))
        self.label_e.setAutoFillBackground(False)
        self.label_e.setStyleSheet(u"background-color:rgb(209, 209, 209)")
        self.label_e.setAlignment(Qt.AlignCenter)
        self.label_q = QLabel(self.centralwidget)
        self.label_q.setObjectName(u"label_q")
        self.label_q.setGeometry(QRect(70, 570, 71, 25))
        self.label_q.setAutoFillBackground(False)
        self.label_q.setStyleSheet(u"background-color:rgb(209, 209, 209)")
        self.label_q.setAlignment(Qt.AlignCenter)
        self.label_u = QLabel(self.centralwidget)
        self.label_u.setObjectName(u"label_u")
        self.label_u.setGeometry(QRect(530, 600, 60, 25))
        self.label_u.setAutoFillBackground(False)
        self.label_u.setStyleSheet(u"background-color:rgb(209, 209, 209)")
        self.label_u.setAlignment(Qt.AlignCenter)
        self.label_o = QLabel(self.centralwidget)
        self.label_o.setObjectName(u"label_o")
        self.label_o.setGeometry(QRect(529, 570, 71, 25))
        self.label_o.setAutoFillBackground(False)
        self.label_o.setStyleSheet(u"background-color:rgb(209, 209, 209)")
        self.label_o.setAlignment(Qt.AlignCenter)
        self.label_action = QLabel(self.centralwidget)
        self.label_action.setObjectName(u"label_action")
        self.label_action.setGeometry(QRect(70, 740, 531, 20))
        self.textBrowser = QTextBrowser(self.centralwidget)
        self.textBrowser.setObjectName(u"textBrowser")
        self.textBrowser.setGeometry(QRect(970, 50, 281, 721))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1260, 22))
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"\u5f00\u59cb", None))
        self.label.setText("")
        self.label_2.setText("")
        self.label_w.setText(QCoreApplication.translate("MainWindow", u"(w)", None))
        self.label_s.setText(QCoreApplication.translate("MainWindow", u"(s)", None))
        self.label_a.setText(QCoreApplication.translate("MainWindow", u"(a)", None))
        self.label_d.setText(QCoreApplication.translate("MainWindow", u"(d)", None))
        self.label_f.setText(QCoreApplication.translate("MainWindow", u"\u4e0a(f)", None))
        self.label_c.setText(QCoreApplication.translate("MainWindow", u"\u5de6(c)", None))
        self.label_b.setText(QCoreApplication.translate("MainWindow", u"\u53f3(b)", None))
        self.label_v.setText(QCoreApplication.translate("MainWindow", u"\u4e0b(v)", None))
        self.label_rl.setText(QCoreApplication.translate("MainWindow", u"(,)", None))
        self.label_rr.setText(QCoreApplication.translate("MainWindow", u"(/)", None))
        self.label_rt.setText(QCoreApplication.translate("MainWindow", u"(;)", None))
        self.label_rb.setText(QCoreApplication.translate("MainWindow", u"(.)", None))
        self.label_j.setText(QCoreApplication.translate("MainWindow", u"Y(j)", None))
        self.label_i.setText(QCoreApplication.translate("MainWindow", u"X(i)", None))
        self.label_l.setText(QCoreApplication.translate("MainWindow", u"A(l)", None))
        self.label_k.setText(QCoreApplication.translate("MainWindow", u"B(k)", None))
        self.label_y.setText(QCoreApplication.translate("MainWindow", u"+(y)", None))
        self.label_r.setText(QCoreApplication.translate("MainWindow", u"-(r)", None))
        self.label_h.setText(QCoreApplication.translate("MainWindow", u"H(h)", None))
        self.label_g.setText(QCoreApplication.translate("MainWindow", u"C(g)", None))
        self.label_x.setText(QCoreApplication.translate("MainWindow", u"(x)", None))
        self.label_rc.setText(QCoreApplication.translate("MainWindow", u"(')", None))
        self.label_e.setText(QCoreApplication.translate("MainWindow", u"L(e)", None))
        self.label_q.setText(QCoreApplication.translate("MainWindow", u"ZL(q)", None))
        self.label_u.setText(QCoreApplication.translate("MainWindow", u"R(u)", None))
        self.label_o.setText(QCoreApplication.translate("MainWindow", u"ZR(o)", None))
        self.label_action.setText(QCoreApplication.translate("MainWindow", u"\u5b9e\u65f6\u547d\u4ee4\uff1a", None))
    # retranslateUi

